# Notifies players with the 'stonks.update-notify' perm
# node when they join the server if a new update is available
# for download. Requires a server reload when changed.
update-notify: true

# How stock prices display in item lores
# Check out 'DecimalFormat java' online for more info
stock-price-decimal-format: '0.##'

# How the amount of shares are displayed in messages
shares-decimal-format: '0.#'

# The time between 2 boards refresh in seconds
board-refresh-time: 30





#The number of data that can be visualised when you see a board/map!
#Also defines the refresh time of the quotation, lower it if your server is overloaded
quotation-data-number : 400


#The impact of the offer and demand on the stock price 1 : maximal and 0 not any impact
offer-demand-impact: 0.5

#The volatily of the stocks 0 is no volatility and 1 is very volatile
#With max volatily and max demandimpact the stocks can change by 10% in 1 hour in the worst case
volatility: 0.5

# The way dates are formatted in the plugin
# Check out 'DateFormat java' online for more info
date-format: 'EEE, d MMM yyyy HH:mm:ss'

# Time during which the stock market is closed,
# ie no shares can be bought or closed.
# Hours must be within 0 and 23
# Minutes must be within 0 and 59
close-time:
  enabled: true
  from:
    hour: 22
    min: 30
  to:
    hour: 4
    min: 0

# Maximum amount of shares owned per player.
# Set to 0 for no limit.
max-shares: 0

# Hour of the day at which dividends are given to players.
dividends-redeem-hour: 10

# How a custom sign displays information about a quotation.
custom-sign-format:
  - '{stock-name}'
  - '${price}'
  - ''
  - '{day-evolution}'
  -
#Custom names for what will displayed in maps, boards and signs
currentpricetext : Current Price
lowestpricetext: Lowest Price
highestpricetext: Highest Price
evolutiontext: Evolution
companynametext : Company Name
stocknametext: Stock Name
timevisualizedtext: Time Visualized
quotationtypetext : Quotation Type
#Adds the name of the company after it
quotationmapnametext : Stock paper of
