# Notifies players with the 'stonks.update-notify' perm
# node when they join the server if a new update is available
# for download. Requires a server reload when changed.
update-notify: true

# How stock prices display in item lores
# Check out 'DecimalFormat java' online for more info
stock-price-decimal-format: '0.##'

# How the amount of shares are displayed in messages
shares-decimal-format: '0.#'

# The time between 2 boards refresh
board-refresh-time: 10

# The way dates are formatted in the plugin
# Check out 'DateFormat java' online for more info
date-format: 'EEE, d MMM yyyy HH:mm:ss'

# Time during which the stock market is closed,
# ie no shares can be bought or closed.
# Hours must be within 0 and 23
# Minutes must be within 0 and 59
close-time:
  enabled: true
  from:
    hour: 22
    min: 30
  to:
    hour: 4
    min: 0

# Maximum amount of shares owned per player.
# Set to 0 for no limit.
max-shares: 0

# Hour of the day at which dividends are given to players.
dividend-redeeem-hour: 10