name: ${project.name}
version: ${project.version}
main: fr.lezoo.stonks
author: [ GMF, Indyuce ]
description: ${project.description}
api-version: 1.13
commands:
  stonks:
    description: 'Main plugin command.'
permissions:
  stonks.admin:
    default: op
