name: ${project.name}
version: ${project.version}
main: fr.lezoo.stonks.Stonks
author: [ GMF, Indyuce ]
depend: [ Vault ]
description: ${project.description}
api-version: 1.13

commands:
  stonks:
    description: 'Main plugin command.'
  portfolio:
    description: 'All you shares are available here.'
  boarddisplay:
    description: 'Display quotation info on an item frame board.'
  removeboard:
    description: 'Removes a quotation display board.'
  redeemdividends:
    description: 'Claims dividends from owned shares.'
  quotations:
    description: 'Displays the list of quotations'
permissions:
  stonks.admin:
    default: op
  stonks.quotation-list:
    description: 'Ability to use /quotations'
    default: op
