name: ${project.name}
version: ${project.version}
main: fr.lezoo.stonks.Stonks
author: [ GMF, Indyuce ]
depend: [ Vault ]
description: ${project.description}
api-version: 1.13
commands:
  stonks:
    description: 'Main plugin command.'
    usage : "Problem with Stonks command"

  boarddisplay :
    description : 'Display a board'
    usage : "Problem with boarddisplay command"

  removeboard :
    description : "allow to remove a board"
    usage : "problem with remove command"
permissions:
  stonks.admin:
    default: op
