name: ${project.name}
version: ${project.version}
main: fr.lezoo.stonks.Stonks
author: [ GMF, Indyuce ]
depend: [ Vault ]
description: ${project.description}
api-version: 1.13
commands:
  stonks:
    description: 'Main plugin command.'

  boarddisplay:
    description: 'Display quotation info on an item frame board.'

  removeboard:
    description: 'Removes a quotation display board.'
permissions:
  stonks.admin:
    default: op
